name: "transformer_pe_groundhog"

data:
    src: "en"
    trg: "de"
    train: "postediting/data/groundhog/train.tok.bpe"
    dev: "postediting/data/groundhog/wmt15-de-en.bpe"
    test: "postediting/data/groundhog/wmt17-de-en.bpe"
    level: "bpe"
    lowercase: False
    max_sent_length: 100
    #src_voc_min_freq: 0
    #trg_voc_min_freq: 0
    src_vocab: "vocab/vocab_ende.txt"  # if specified, load a vocabulary from this file
    trg_vocab: "vocab/vocab_ende.txt"  # one token per line, line number is index

testing:
    beam_size: 5
    alpha: 1.0

training:
    #load_model: "models/sy_transformer_copy_1/best.ckpt"
    reset_best_ckpt: True
    reset_scheduler: True
    reset_optimizer: True
    random_seed: 42
    optimizer: "adam"
    normalization: "tokens"
    adam_betas: [0.9, 0.999]
    scheduling: "plateau"
    patience: 8
    decrease_factor: 0.7
    loss: "crossentropy"
    learning_rate: 0.0002
    learning_rate_min: 0.00000001
    weight_decay: 0.0
    label_smoothing: 0.1
    batch_size: 4000
    batch_type: "token"
    eval_batch_size: 3600
    eval_batch_type: "token"
    batch_multiplier: 1
    early_stopping_metric: "ppl"
    epochs: 100
    validation_freq: 4000
    logging_freq: 200
    eval_metric: "bleu"
    model_dir: "models/sy_transformer_wmt17_ende_groundhog_3"
    overwrite: True
    shuffle: True
    use_cuda: True
    max_output_length: 100
    print_valid_sents: [0, 1, 2]
    keep_last_ckpts: 2

model:
    initializer: "xavier"
    bias_initializer: "zeros"
    init_gain: 1.0
    embed_initializer: "xavier"
    embed_init_gain: 1.0
    tied_embeddings: True
    tied_softmax: True
    encoder:
        type: "transformer"
        num_layers: 6
        num_heads: 8
        embeddings:
            embedding_dim: 512
            scale: True
            dropout: 0.
        # typically ff_size = 4 x hidden_size
        hidden_size: 512
        ff_size: 2048
        dropout: 0.1
    decoder:
        type: "transformer"
        num_layers: 6
        num_heads: 8
        embeddings:
            embedding_dim: 512
            scale: True
            dropout: 0.
        # typically ff_size = 4 x hidden_size
        hidden_size: 512
        ff_size: 2048
        dropout: 0.1
