name: "sy_experiment_1"

data:
    src: "de"
    trg: "en"
    train: "postediting/data/multi30k/train.lc.norm.tok"
    dev: "postediting/data/multi30k/dev_2017_flickr.lc.norm.tok"
    random_train_subset: 10000
    level: "word"
    lowercase: False
    max_sent_length: 50
    src_voc_min_freq: 1
    trg_voc_min_freq: 1

testing:
    beam_size: 5
    alpha: 1.0

training:
    load_model: "models/sy_transformer_copy_1/best.ckpt"
    reset_best_ckpt: False
    reset_scheduler: False
    reset_optimizer: False
    random_seed: 42
    optimizer: "adam"
    adam_betas: [0.9, 0.999]
    scheduling: "plateau"
    loss: "crossentropy"
    learning_rate: 0.0002
    learning_rate_min: 0.00000001
    #learning_rate_factor: 2   # factor for Noam scheduler (default: 1)
    learning_rate_warmup: 5000  # warmup steps for Noam scheduler
    #label_smoothing: 0.1
    weight_decay: 0.0
    batch_size: 64
    batch_type: "token"
    eval_batch_size: 10             # mini-batch size for evaluation (see batch_size above)
    eval_batch_type: "token"     # evaluation batch type ("sentence", default) or tokens ("token")
    epochs: 100
    early_stopping_metric: "ppl"
    validation_freq: 4000
    logging_freq: 200
    eval_metric: "token_accuracy"
    model_dir: "models/sy_transformer_copy_1"
    overwrite: True
    shuffle: True
    use_cuda: True
    max_output_length: 50
    print_valid_sents: [0, 1, 2]
    keep_last_ckpts: 3

model:
    initializer: "xavier"           # initializer for all trainable weights (xavier, zeros, normal, uniform)
    init_gain: 1.0                  # gain for Xavier initializer (default: 1.0)
    bias_initializer: "zeros"       # initializer for bias terms (xavier, zeros, normal, uniform)
    embed_initializer: "xavier"     # initializer for embeddings (xavier, zeros, normal, uniform)
    embed_init_gain: 1.0            # gain for Xavier initializer for embeddings (default: 1.0)
    tied_embeddings: False          # tie src and trg embeddings, only applicable if vocabularies are the same, default: False
    tied_softmax: True
    encoder:
        type: "transformer"
        num_layers: 2
        num_heads: 4
        embeddings:
            embedding_dim: 64
            scale: True
            dropout: 0.
        # typically ff_size = 4 x hidden_size
        hidden_size: 64
        ff_size: 256
        dropout: 0.1
    decoder:
        type: "transformer"
        num_layers: 2
        num_heads: 4
        embeddings:
            embedding_dim: 64
            scale: True
            dropout: 0.
        # typically ff_size = 4 x hidden_size
        hidden_size: 64
        ff_size: 256
        dropout: 0.1
